// Code generated by mockery v2.46.3. DO NOT EDIT.

package measurements

import (
	measurements "asset-measurements-assignment/internal/domain/measurements"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// AddMeasurement provides a mock function with given fields: ctx, assetId, measurement
func (_m *MockRepository) AddMeasurement(ctx context.Context, assetId string, measurement measurements.Measurement) error {
	ret := _m.Called(ctx, assetId, measurement)

	if len(ret) == 0 {
		panic("no return value specified for AddMeasurement")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, measurements.Measurement) error); ok {
		r0 = rf(ctx, assetId, measurement)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_AddMeasurement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMeasurement'
type MockRepository_AddMeasurement_Call struct {
	*mock.Call
}

// AddMeasurement is a helper method to define mock.On call
//   - ctx context.Context
//   - assetId string
//   - measurement measurements.Measurement
func (_e *MockRepository_Expecter) AddMeasurement(ctx interface{}, assetId interface{}, measurement interface{}) *MockRepository_AddMeasurement_Call {
	return &MockRepository_AddMeasurement_Call{Call: _e.mock.On("AddMeasurement", ctx, assetId, measurement)}
}

func (_c *MockRepository_AddMeasurement_Call) Run(run func(ctx context.Context, assetId string, measurement measurements.Measurement)) *MockRepository_AddMeasurement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(measurements.Measurement))
	})
	return _c
}

func (_c *MockRepository_AddMeasurement_Call) Return(_a0 error) *MockRepository_AddMeasurement_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_AddMeasurement_Call) RunAndReturn(run func(context.Context, string, measurements.Measurement) error) *MockRepository_AddMeasurement_Call {
	_c.Call.Return(run)
	return _c
}

// GetAssetMeasurements provides a mock function with given fields: ctx, assetID, timeRange
func (_m *MockRepository) GetAssetMeasurements(ctx context.Context, assetID string, timeRange measurements.TimeRange) ([]measurements.Measurement, error) {
	ret := _m.Called(ctx, assetID, timeRange)

	if len(ret) == 0 {
		panic("no return value specified for GetAssetMeasurements")
	}

	var r0 []measurements.Measurement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, measurements.TimeRange) ([]measurements.Measurement, error)); ok {
		return rf(ctx, assetID, timeRange)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, measurements.TimeRange) []measurements.Measurement); ok {
		r0 = rf(ctx, assetID, timeRange)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]measurements.Measurement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, measurements.TimeRange) error); ok {
		r1 = rf(ctx, assetID, timeRange)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetAssetMeasurements_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAssetMeasurements'
type MockRepository_GetAssetMeasurements_Call struct {
	*mock.Call
}

// GetAssetMeasurements is a helper method to define mock.On call
//   - ctx context.Context
//   - assetID string
//   - timeRange measurements.TimeRange
func (_e *MockRepository_Expecter) GetAssetMeasurements(ctx interface{}, assetID interface{}, timeRange interface{}) *MockRepository_GetAssetMeasurements_Call {
	return &MockRepository_GetAssetMeasurements_Call{Call: _e.mock.On("GetAssetMeasurements", ctx, assetID, timeRange)}
}

func (_c *MockRepository_GetAssetMeasurements_Call) Run(run func(ctx context.Context, assetID string, timeRange measurements.TimeRange)) *MockRepository_GetAssetMeasurements_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(measurements.TimeRange))
	})
	return _c
}

func (_c *MockRepository_GetAssetMeasurements_Call) Return(_a0 []measurements.Measurement, _a1 error) *MockRepository_GetAssetMeasurements_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetAssetMeasurements_Call) RunAndReturn(run func(context.Context, string, measurements.TimeRange) ([]measurements.Measurement, error)) *MockRepository_GetAssetMeasurements_Call {
	_c.Call.Return(run)
	return _c
}

// GetAssetMeasurementsAveraged provides a mock function with given fields: ctx, assetID, params
func (_m *MockRepository) GetAssetMeasurementsAveraged(ctx context.Context, assetID string, params measurements.AssetMeasurementAveragedParams) ([]measurements.Measurement, error) {
	ret := _m.Called(ctx, assetID, params)

	if len(ret) == 0 {
		panic("no return value specified for GetAssetMeasurementsAveraged")
	}

	var r0 []measurements.Measurement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, measurements.AssetMeasurementAveragedParams) ([]measurements.Measurement, error)); ok {
		return rf(ctx, assetID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, measurements.AssetMeasurementAveragedParams) []measurements.Measurement); ok {
		r0 = rf(ctx, assetID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]measurements.Measurement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, measurements.AssetMeasurementAveragedParams) error); ok {
		r1 = rf(ctx, assetID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetAssetMeasurementsAveraged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAssetMeasurementsAveraged'
type MockRepository_GetAssetMeasurementsAveraged_Call struct {
	*mock.Call
}

// GetAssetMeasurementsAveraged is a helper method to define mock.On call
//   - ctx context.Context
//   - assetID string
//   - params measurements.AssetMeasurementAveragedParams
func (_e *MockRepository_Expecter) GetAssetMeasurementsAveraged(ctx interface{}, assetID interface{}, params interface{}) *MockRepository_GetAssetMeasurementsAveraged_Call {
	return &MockRepository_GetAssetMeasurementsAveraged_Call{Call: _e.mock.On("GetAssetMeasurementsAveraged", ctx, assetID, params)}
}

func (_c *MockRepository_GetAssetMeasurementsAveraged_Call) Run(run func(ctx context.Context, assetID string, params measurements.AssetMeasurementAveragedParams)) *MockRepository_GetAssetMeasurementsAveraged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(measurements.AssetMeasurementAveragedParams))
	})
	return _c
}

func (_c *MockRepository_GetAssetMeasurementsAveraged_Call) Return(_a0 []measurements.Measurement, _a1 error) *MockRepository_GetAssetMeasurementsAveraged_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetAssetMeasurementsAveraged_Call) RunAndReturn(run func(context.Context, string, measurements.AssetMeasurementAveragedParams) ([]measurements.Measurement, error)) *MockRepository_GetAssetMeasurementsAveraged_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestAssetMeasurement provides a mock function with given fields: ctx, assetID
func (_m *MockRepository) GetLatestAssetMeasurement(ctx context.Context, assetID string) (*measurements.Measurement, error) {
	ret := _m.Called(ctx, assetID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestAssetMeasurement")
	}

	var r0 *measurements.Measurement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*measurements.Measurement, error)); ok {
		return rf(ctx, assetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *measurements.Measurement); ok {
		r0 = rf(ctx, assetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*measurements.Measurement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, assetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetLatestAssetMeasurement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestAssetMeasurement'
type MockRepository_GetLatestAssetMeasurement_Call struct {
	*mock.Call
}

// GetLatestAssetMeasurement is a helper method to define mock.On call
//   - ctx context.Context
//   - assetID string
func (_e *MockRepository_Expecter) GetLatestAssetMeasurement(ctx interface{}, assetID interface{}) *MockRepository_GetLatestAssetMeasurement_Call {
	return &MockRepository_GetLatestAssetMeasurement_Call{Call: _e.mock.On("GetLatestAssetMeasurement", ctx, assetID)}
}

func (_c *MockRepository_GetLatestAssetMeasurement_Call) Run(run func(ctx context.Context, assetID string)) *MockRepository_GetLatestAssetMeasurement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetLatestAssetMeasurement_Call) Return(_a0 *measurements.Measurement, _a1 error) *MockRepository_GetLatestAssetMeasurement_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetLatestAssetMeasurement_Call) RunAndReturn(run func(context.Context, string) (*measurements.Measurement, error)) *MockRepository_GetLatestAssetMeasurement_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
