// Code generated by mockery v2.46.3. DO NOT EDIT.

package assets

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateAsset provides a mock function with given fields: ctx, asset
func (_m *MockRepository) CreateAsset(ctx context.Context, asset Asset) (*Asset, error) {
	ret := _m.Called(ctx, asset)

	if len(ret) == 0 {
		panic("no return value specified for CreateAsset")
	}

	var r0 *Asset
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, Asset) (*Asset, error)); ok {
		return rf(ctx, asset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, Asset) *Asset); ok {
		r0 = rf(ctx, asset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Asset)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, Asset) error); ok {
		r1 = rf(ctx, asset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAsset'
type MockRepository_CreateAsset_Call struct {
	*mock.Call
}

// CreateAsset is a helper method to define mock.On call
//   - ctx context.Context
//   - asset Asset
func (_e *MockRepository_Expecter) CreateAsset(ctx interface{}, asset interface{}) *MockRepository_CreateAsset_Call {
	return &MockRepository_CreateAsset_Call{Call: _e.mock.On("CreateAsset", ctx, asset)}
}

func (_c *MockRepository_CreateAsset_Call) Run(run func(ctx context.Context, asset Asset)) *MockRepository_CreateAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(Asset))
	})
	return _c
}

func (_c *MockRepository_CreateAsset_Call) Return(_a0 *Asset, _a1 error) *MockRepository_CreateAsset_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateAsset_Call) RunAndReturn(run func(context.Context, Asset) (*Asset, error)) *MockRepository_CreateAsset_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAsset provides a mock function with given fields: ctx, assetId
func (_m *MockRepository) DeleteAsset(ctx context.Context, assetId string) error {
	ret := _m.Called(ctx, assetId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAsset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, assetId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAsset'
type MockRepository_DeleteAsset_Call struct {
	*mock.Call
}

// DeleteAsset is a helper method to define mock.On call
//   - ctx context.Context
//   - assetId string
func (_e *MockRepository_Expecter) DeleteAsset(ctx interface{}, assetId interface{}) *MockRepository_DeleteAsset_Call {
	return &MockRepository_DeleteAsset_Call{Call: _e.mock.On("DeleteAsset", ctx, assetId)}
}

func (_c *MockRepository_DeleteAsset_Call) Run(run func(ctx context.Context, assetId string)) *MockRepository_DeleteAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_DeleteAsset_Call) Return(_a0 error) *MockRepository_DeleteAsset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteAsset_Call) RunAndReturn(run func(context.Context, string) error) *MockRepository_DeleteAsset_Call {
	_c.Call.Return(run)
	return _c
}

// GetAsset provides a mock function with given fields: ctx, assetId
func (_m *MockRepository) GetAsset(ctx context.Context, assetId string) (*Asset, error) {
	ret := _m.Called(ctx, assetId)

	if len(ret) == 0 {
		panic("no return value specified for GetAsset")
	}

	var r0 *Asset
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*Asset, error)); ok {
		return rf(ctx, assetId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *Asset); ok {
		r0 = rf(ctx, assetId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Asset)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, assetId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAsset'
type MockRepository_GetAsset_Call struct {
	*mock.Call
}

// GetAsset is a helper method to define mock.On call
//   - ctx context.Context
//   - assetId string
func (_e *MockRepository_Expecter) GetAsset(ctx interface{}, assetId interface{}) *MockRepository_GetAsset_Call {
	return &MockRepository_GetAsset_Call{Call: _e.mock.On("GetAsset", ctx, assetId)}
}

func (_c *MockRepository_GetAsset_Call) Run(run func(ctx context.Context, assetId string)) *MockRepository_GetAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetAsset_Call) Return(_a0 *Asset, _a1 error) *MockRepository_GetAsset_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetAsset_Call) RunAndReturn(run func(context.Context, string) (*Asset, error)) *MockRepository_GetAsset_Call {
	_c.Call.Return(run)
	return _c
}

// GetAssets provides a mock function with given fields: ctx, query
func (_m *MockRepository) GetAssets(ctx context.Context, query AssetQuery) ([]Asset, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetAssets")
	}

	var r0 []Asset
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, AssetQuery) ([]Asset, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, AssetQuery) []Asset); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Asset)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, AssetQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetAssets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAssets'
type MockRepository_GetAssets_Call struct {
	*mock.Call
}

// GetAssets is a helper method to define mock.On call
//   - ctx context.Context
//   - query AssetQuery
func (_e *MockRepository_Expecter) GetAssets(ctx interface{}, query interface{}) *MockRepository_GetAssets_Call {
	return &MockRepository_GetAssets_Call{Call: _e.mock.On("GetAssets", ctx, query)}
}

func (_c *MockRepository_GetAssets_Call) Run(run func(ctx context.Context, query AssetQuery)) *MockRepository_GetAssets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(AssetQuery))
	})
	return _c
}

func (_c *MockRepository_GetAssets_Call) Return(_a0 []Asset, _a1 error) *MockRepository_GetAssets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetAssets_Call) RunAndReturn(run func(context.Context, AssetQuery) ([]Asset, error)) *MockRepository_GetAssets_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAsset provides a mock function with given fields: ctx, assetId, asset
func (_m *MockRepository) UpdateAsset(ctx context.Context, assetId string, asset Asset) (*Asset, error) {
	ret := _m.Called(ctx, assetId, asset)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAsset")
	}

	var r0 *Asset
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, Asset) (*Asset, error)); ok {
		return rf(ctx, assetId, asset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, Asset) *Asset); ok {
		r0 = rf(ctx, assetId, asset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Asset)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, Asset) error); ok {
		r1 = rf(ctx, assetId, asset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_UpdateAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAsset'
type MockRepository_UpdateAsset_Call struct {
	*mock.Call
}

// UpdateAsset is a helper method to define mock.On call
//   - ctx context.Context
//   - assetId string
//   - asset Asset
func (_e *MockRepository_Expecter) UpdateAsset(ctx interface{}, assetId interface{}, asset interface{}) *MockRepository_UpdateAsset_Call {
	return &MockRepository_UpdateAsset_Call{Call: _e.mock.On("UpdateAsset", ctx, assetId, asset)}
}

func (_c *MockRepository_UpdateAsset_Call) Run(run func(ctx context.Context, assetId string, asset Asset)) *MockRepository_UpdateAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(Asset))
	})
	return _c
}

func (_c *MockRepository_UpdateAsset_Call) Return(_a0 *Asset, _a1 error) *MockRepository_UpdateAsset_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_UpdateAsset_Call) RunAndReturn(run func(context.Context, string, Asset) (*Asset, error)) *MockRepository_UpdateAsset_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
