on:
  workflow_call:
    inputs:
      service:
        description: The service to build
        type: string
        required: true
      dockerfile:
        description: Path to Dockerfile
        type: string
        required: true
jobs:

  # Build Docker image
  build-service:
    name: Build ${{ inputs.service }} service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: asset-${{ inputs.service }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Cache Docker layers
        uses: actions/cache@v4.0.2
        with:
          path: go-build-cache
          key: ${{ runner.os }}-go-build-cache-${{ hashFiles('**/go.sum') }}

      - name: inject go-build-cache into docker
        # v1 was composed of two actions: "inject" and "extract".
        # v2 is unified to a single action.
        uses: reproducible-containers/buildkit-cache-dance@v3.1.2
        with:
          cache-source: go-build-cache
          cache-map: ''

      # Build Docker image with Buildx
      - name: Build Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          file: ${{ inputs.dockerfile }}
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
