name: "Build services"
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - 'deployment/**'
      - '*.md'
    tags:
      - v*

  pull_request:
    types: [ opened, synchronize ]
    branches:
      - main
    paths-ignore:
      - 'deployment/**'
      - '*.md'
  workflow_dispatch:

jobs:

  build-asset-service:
    name: "Build Asset service"
    uses: ./.github/workflows/build.yaml
    with:
      service: asset-service
      dockerfile: "./build/asset-service/Dockerfile"
    secrets: inherit

  build-simulator-service:
    name: "Build Simulator service"
    uses: ./.github/workflows/build.yaml
    with:
      service: simulator
      dockerfile: "./build/simulator/Dockerfile"
    secrets: inherit
