name: "Build services"
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - 'docs/**'
      - 'api/**'
      - 'config/**'
      - 'deployments/**'
      - '*.md'
    tags:
      - v*

  pull_request:
    types: [ opened, synchronize ]
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'api/**'
      - 'deployments/**'
      - '*.md'
  workflow_dispatch:

jobs:

  build-asset-service:
    name: "Build and Push Asset service"
    uses: ./.github/workflows/build.yaml
    with:
      service: asset
      push: false
      docker_repository: asset-service
      dockerfile: "./build/asset-service/Dockerfile"
    secrets: inherit

  build-simulator-service:
    name: "Build and Push Simulator service"
    uses: ./.github/workflows/build.yaml
    with:
      service: simulator-service
      push: false
      docker_repository: simulator_service
      dockerfile: "./build/simulator-service/Dockerfile"
    secrets: inherit
